name: Ruleset10_Override_Housing_Purpose
description: Contains rule for overriding housing purpose
version: '2.2'
author: nathan+business@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: ruleset10overridehousingpurpose
  parentArtefactID: westpacbusiness
  buildSystem: wheel
  author: null
  createdAt: '2024-05-23 00:43:52'
pipelines:
  pipelines/test_rule:
    name: Test_OverrideHousingPurpose
    description: Ruleset that includes rules for overriding housing purpose.
    author: nathan+business@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-05-23 00:43:52'
    datasets:
      inputs:
      - datasets/sample_data
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/sample_data:
    name: housingpurposeid_sampledata
    description: ''
    author: nathan+business@prophecy.io
    createdAt: '2024-05-23 01:18:25'
    mode: batch
    physicalDatasets:
      DatabricksCluster:
        fabricId: 117
        datasetType: Database
        description: ''
        author: nathan+business@prophecy.io
        createdAt: '2024-05-23 01:18:25'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems:
    gems/AddRule:
      name: AddRule
      category: Transform
      subCategory: ''
      description: null
      author: nathan+business@prophecy.io
      mode: batch
      files:
      - westpacbusiness_ruleset10overridehousingpurpose/gems/AddRule.py
      gemType: ComponentGem
      dependencies: []
      createdAt: '2024-05-23 00:59:53'
  dependencies: null
functions:
  author: null
  createdAt: '2024-05-23 00:43:52'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules:
    businessRules/Override_Housing_Purpose:
      name: Override_Housing_Purpose
      description: Rule to override housing purposes
      tags: []
      inputs: []
      outputs: []
      author: nathan+business@prophecy.io
      createdAt: '2022-12-15 18:04:50'
    businessRules/Override_EFS_Rule_Id:
      name: Override_EFS_Rule_Id
      description: This overrides EFS Rule ID based on certain conditions
      tags: []
      inputs: []
      outputs: []
      author: nathan+business@prophecy.io
      createdAt: '2022-12-15 18:04:50'
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-06-19T20:24:43.638683Z'
  name: plibMaven
  version: 8.0.11
  id: '325327305'
  createdAt: '2024-06-19T20:24:43.638649Z'
- type: plibPypi
  modifiedAt: '2024-06-19T20:24:43.638729Z'
  name: plibPypi
  version: 1.9.5
  id: '2010666717'
  createdAt: '2024-06-19T20:24:43.638722Z'
projectDependencies:
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-06-19 20:25:06'
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.25
    isDefault: true
    author: null
    createdAt: '2024-06-19 20:25:02'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
